## MDS(Multi Dimensional Scaling)
- 객체들간의 거리를 바탕으로 유사성을 측정하여 다차원 공간에 표현하는 분석 방법입니다
- 기존 데이터들간의 거리 정보를 최대한 보존하는 좌표계를 찾고자 합니다
- MDS에서는 모든 점들간의 거리 정보의 중요도를 같게 다루기 때문에 고차원의 원 공간에서 가까운 거리를 가지는 점들간의 구조를 잘 보존하지 못한다는 한계점이 있습니다

In [1]:
from numpy.linalg import eig
from sklearn.manifold import TSNE
from sklearn.datasets import load_digits
from sklearn.preprocessing import StandardScaler
import numpy as np 
import pandas as pd
import seaborn as sns
from IPython.display import Image

<b>MDS 과정<b>

1. 근접 거리 행렬 구축
2. 개체 간의 거리 정보를 잘 보존하는 좌표계 추출
3. 추출한 좌표계에 데이터를 mapping하고 분석

### Vector X에 대한 MDS를 찾아보자

In [2]:
data = np.array([[1,1],[1,-1],[-1,1],[-1,-1]])
data

array([[ 1,  1],
       [ 1, -1],
       [-1,  1],
       [-1, -1]])

1. Gram 매트릭스를 계산합니다

![nn](./images/GRAM.png)

-   해당 매트릭스의 제약조건은 다음과 같습니다

![nn1](./images/GRAM_COND.png)

In [3]:
mat = data.dot(data.T)
print('Gram 매트릭스:\n',mat)

Gram 매트릭스:
 [[ 2  0  0 -2]
 [ 0  2 -2  0]
 [ 0 -2  2  0]
 [-2  0  0  2]]


2. Gram 매트릭스의 eigen value값과 eigen vector를 계산합니다

![nn](./images/EIGEN.png)

In [4]:
eigen_val = eig(mat)[0]
eigen_vec = eig(mat)[1]

In [5]:
eigen_val.shape

(4,)

In [6]:
eigen_vec.shape

(4, 4)

In [7]:
# 각각의 eigen value값에 대응되는 eigen vector 찾기
print(f' {eigen_val[0]} 에 대응되는 eigen vector :', eigen_vec[:,0])
print(f' {eigen_val[1]} 에 대응되는 eigen vector :', eigen_vec[:,1])
print(f' {eigen_val[2]} 에 대응되는 eigen vector :', eigen_vec[:,2])

 4.0 에 대응되는 eigen vector : [ 0.70710678  0.          0.         -0.70710678]
 4.440892098500626e-16 에 대응되는 eigen vector : [0.70710678 0.         0.         0.70710678]
 4.0 에 대응되는 eigen vector : [ 0.         -0.70710678  0.70710678  0.        ]


In [8]:
print(f'\n MDS Axis : {eigen_vec[:,0]} (최대 eigen value λ에 대응되는 eigen vector) = {eigen_val[0]}')


 MDS Axis : [ 0.70710678  0.          0.         -0.70710678] (최대 eigen value λ에 대응되는 eigen vector) = 4.0


In [9]:
mds_axis = eigen_vec[:,0]
mds_axis

array([ 0.70710678,  0.        ,  0.        , -0.70710678])

3. X를 V1에 projection 시킨 결과는 다음과 같이 표현할 수 있습니다

![nn](./images/PROJ_Y.png)

In [10]:
proj_XonMDS = np.linalg.norm(mds_axis.dot(data)/np.linalg.norm(mds_axis))*mds_axis/np.linalg.norm(mds_axis)
print('X 벡터를 R(3*1)에 해당되는 Y에 project 시켰을 때 (q=1) :\n',proj_XonMDS)

X 벡터를 R(3*1)에 해당되는 Y에 project 시켰을 때 (q=1) :
 [ 1.41421356  0.          0.         -1.41421356]
